### ISSUE TITLE
Following "Piratebox on SD card" instructions puts PirateBox into emergency mode

### ISSUE THREAD

**Issue by crypdick** [LibraryBox-Dev/package-arch-librarybox-config#8]
I followed the [install instructions](https://piratebox.cc/raspberry_pi:mods#piratebox_on_sdcard) on how to use the rest of my microSD card for storage space. On start-up, I'd get a bunch of errors and my RPi3 goes into emergency mode.

[Ouput of `journalctl -xb`](https://gist.github.com/crypdick/c0b5a9be3a04eb8baa28d6126e2c0d72)
(P.S. I saw the errors about not being able to mount EXT3 or EXT2 filesystems. The partition which was bound to become `/mnt/sdcard` was formatted FAT32. I tried to reformat it EXT2 and boot the Piratebox again but I go the same error.)

I am not really fluent in bash, but I took a peek at `lbx_functions.sh` and noticed that at the top it declares
```bash
SWAP_PARTITION="/dev/mmcblk0p3"
EXT_PARTITION="/dev/mmcblk0p4"
```

...when according to gparted swap is on `/dev/mmcblk0p2` and the `/mnt/sdcard` partition is `/dev/mmcblk0p3`. I don't know if that's the problem right there.

v `piratebox_rpi2_1.1.1-1-03-10-2016.img`

**Comment by MaStr** [comment]
Hi,
okey.. first I was totally confused about that issue.. but it is getting clear now.

Ok. Let me sort out some things here:

p1 is always FAT32, because it contains the bootloader and the config files for RPi
p2 is the root partition.

So, this is the default, which we use to generate the rpi image for PirateBox

Until this point

````
SWAP_PARTITION="/dev/mmcblk0p3"
EXT_PARTITION="/dev/mmcblk0p4"
````
is correct.

The command:   sudo cli_lbx.sh do_swapon_step1

Does: 
   1. Create a new swap partition as the next free primary partition 
   2. Choose number 3
   3. Size 265MB
   4. Enable startup service for preparing the swap

The command:   sudo cli_lbx.sh do_ext_step1

Does
  1.  Create a new partition as a primary
  2. Choose Number 4
  3. Take all free space (default values)
  4. Enable a startup service for prearping the ext-space

After a reboot, the following is happening:

 1. do_swapon_step2  is executed by systemd
 1.1. it formats the partition on p3 as swap
 1.2. Creates the entry in fstab
 1.3. Disables the boot up service
 1.4. Enables the swap
 2.  do_ext_step2
 2.1. Creates an ext4 partition on p4
 2.2. Creates an entry in fstab
 2.3. disables bootup service for the extended partiiton
 2.4. mounts the mount-point


This looks ok to me.

The journal-output shows what you described, but I wonder how that did happen... 

I am downloading the image now to verify the partition table.

**Comment by MaStr** [comment]
I verified the image file. That looks as expected:
> 
> [matze@shrimpy 111_rpi]$ unzip piratebox_rpi2_1.1.1-1-03-10-2016.img.zip 
> Archive:  piratebox_rpi2_1.1.1-1-03-10-2016.img.zip
>   inflating: piratebox_rpi2_1.1.1-1-03-10-2016.img  
> [matze@shrimpy 111_rpi]$ sudo losetup -f -P piratebox_rpi2_1.1.1-1-03-10-2016.img
> [sudo] password for matze: 
> [matze@shrimpy 111_rpi]$ 
> [matze@shrimpy 111_rpi]$ 
> [matze@shrimpy 111_rpi]$ ls
> piratebox_rpi2_1.1.1-1-03-10-2016.img  piratebox_rpi2_1.1.1-1-03-10-2016.img.zip
> [matze@shrimpy 111_rpi]$ sudo fdisk /dev/loop0
> 
> Welcome to fdisk (util-linux 2.29).
> Changes will remain in memory only, until you decide to write them.
> Be careful before using the write command.
> 
> 
> Command (m for help): p
> Disk /dev/loop0: 2 GiB, 2147483648 bytes, 4194304 sectors
> Units: sectors of 1 * 512 = 512 bytes
> Sector size (logical/physical): 512 bytes / 512 bytes
> I/O size (minimum/optimal): 512 bytes / 512 bytes
> Disklabel type: dos
> Disk identifier: 0xbb17c2e8
> 
> Device       Boot  Start     End Sectors  Size Id Type
> /dev/loop0p1        2048  206847  204800  100M  c W95 FAT32 (LBA)
> /dev/loop0p2      206848 4194303 3987456  1.9G 83 Linux
> 
> Command (m for help): 
>

**Comment by crypdick** [comment]
¯\_(ツ)_/¯
I was able to get my Piratebox to use the rest of my storage without running those shell scripts. I reflashed my RPi3 and in gparted I made a new ext3 partition for `Shared`. Then, I manually added an entry for `/mnt/sdcard` in `fstab` and restarted. Moved `Shared` to the new partition, made the symbolic links to `/opt/`. Everything appears to be functioning... do you think not having swap will give me trouble?
